### ISSUE TITLE
1.16.5?

### ISSUE THREAD

**Issue by srnyx** [Sintinium/oauth-fabric#1]
Are you going to add support for 1.16.5?

**Comment by Sintinium** [comment]
Yes, I'll probably have a version up tomorrow for 1.16.5

**Comment by srnyx** [comment]
> Yes, I'll probably have a version up tomorrow for 1.16.5

Awesome! Thank you :D

**Comment by Sintinium** [comment]
Just wanted to let you know that it's now on curseforge! https://www.curseforge.com/minecraft/mc-mods/oauth-fabric/files/3453291
