### ISSUE TITLE
Mojang Account - Text Fields "stutter"

### ISSUE THREAD

**Issue by LezChap** [Sintinium/oauth-fabric#2]
When trying to log into an Mojang account, the text fields stutter, and input is sometimes ignored.  It almost appears like it's altering focus between the username/email and password text fields, but "lost" keypresses don't go into the wrong field, so I don't think that's actually what's happening.

The password field's "cursor" is also half-way across the field...and the password is not obfuscated on input (not sure if that's intended).
https://i.imgur.com/EgIMUt7.png
https://i.imgur.com/Y4TCifb.png

Versions:
Minecraft - 1.18
Fabric - 0.12.9  (also happened on 0.12.8)
OAuth - 1.1.4

This happens even on a clean install with no other mods.

**Comment by Sintinium** [comment]
Fixed in the most recent version. Thanks for the report :)
