### ISSUE TITLE
Latest release 1.1.4.1 does not work with 1.18.1

### ISSUE THREAD

**Issue by znopp** [Sintinium/oauth-fabric#3]
I tried adding the latest release, oauth-fabric-1.1.4.1 which is listed to be compatible with 1.18.1, to my mods folder and start the game (running on 1.18.1). It won't start because it is "not compatible" with the Minecraft version. Pastebin of my stracktrace: https://pastebin.com/KwpuA20u

On latest fabric version 0.12.11

Reproduce by adding the mod to your mods folder, along with fabric API, and starting the game.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/82549089/145854616-07767c6f-2139-4eb7-941e-95593b0b884d.png)

same here

**Comment by Sintinium** [comment]
I didn't realize 1.18.1 wasn't compatible with 1.18 mods. I'll have an update out soon :)

**Comment by Sintinium** [comment]
Fixed in the most recent version!
