### ISSUE TITLE
wont connect

### ISSUE THREAD

**Issue by Dogrubb** [Sintinium/oauth-fabric#5]
i was trying to connect my microsoft account to the mod on 1.17.1 but it wouldnt connect even after i gave it permission and it said you can close your browser

**Comment by Sintinium** [comment]
I'll have an update out that should fix this in a few days.

**Comment by Sintinium** [comment]
As of now I don't plan on supporting 1.17 any longer. If you have this issue on other versions please let me know. Sorry for the inconvenience
