### ISSUE TITLE
Instantly crashed when i just clicked the button

### ISSUE THREAD

**Issue by MyNameIsF** [Sintinium/oauth-fabric#6]
[crash-2022-03-21_17.44.16-client.txt](https://github.com/Sintinium/oauth-fabric/files/8316355/crash-2022-03-21_17.44.16-client.txt)

**Comment by alext** [comment]
It looks like the 1.1.4.1 version isn't compatible with minecraft 1.18.2. I'm getting the same error when trying to use this with 1.18.2.

**Comment by Sintinium** [comment]
Update to the latest version. 1.18.2 is now on curseforge :)
